### ISSUE TITLE
Make click event handlers run asynchronously to prevent blocking UI

### ISSUE THREAD

**Issue by pirate** [dugwood/clickheat#6] opened 2016-05-19 21:26 UTC
https://github.com/piwikjapan/plugin-clickheat/pull/21

Not sure which project is the active one?

**Comment by dugwood** [comment] 2016-05-21 07:25
It's this one. But there have been no releases since a long time (didn't have the time to do so, and clickheat v2.0 with database support is too much work for now).

The fix doesn't seem to be good to me: it only differs the execution by 20ms, but the execution is already asynchronous (function is launched anyway).

The culprit would be: https://github.com/dugwood/clickheat/blob/master/js/clickheat-original.js#L237:L241
=> wait for 500ms before leaving the rest of the code.

If you add the 20ms delay, then this very code has no use. The problem is that:
- user clicks a link
- browser destroy the whole environment of the page, including ClickHeat
- no click is tracked
  Hence the blocking code...

There may be other solutions (but popup is not a good one even if it would probably work), but for now I don't know which one... The code was took from piwik, in the tracking of external links (IIRC).

What are your thoughts about that? If you want to remove the blocking, you can set the clickHeatWait variable to zero.

**Comment by pirate** [comment] 2016-05-24 21:29
My PR is a very naive solution, certainly not production-ready, I just wanted to see if anyone had similar ideas or solutions.

We could probably hack something together with a webworker that has a long-running task which checks if the page is still open.

http://stackoverflow.com/questions/20084348/what-happens-to-a-web-worker-if-i-close-the-page-that-created-this-web-worker

**Comment by dugwood** [comment] 2016-05-25 06:57
It doesn't seem to do the job: 

> does not allow it to handle any further events (worker messages, timers, network communication callbacks, etc.).

I'll have a look at it, but if you can run tests with clickHeatWait set to 0, and tell me if the clicks are tracked... Use the debug mode also: append `?debugclickheat` at the end of the url and reload it, you should see a debug box at the top left of the page.

**Comment by dugwood** [comment] 2016-10-08 13:33
I'm closing this for now. Setting 0 is one way to do avoid that.

**Closed as completed by dugwood** 2016-10-08 13:33 UTC
